spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testsql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
  application:
    name: emp-service

mybatis-plus:
  type-aliases-package: com.cheer.emp.model
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    org.springframework.web: error
    com.cheer.emp.web: trace

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka,http://127.0.0.1:8083/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

